name = "brick-email-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

# Email Routing
[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.email_routing.matchers]]
pattern = "*@afonsoingles.dev"

[env.development]
vars = { ENVIRONMENT = "development" }

# Observability
[observability]
enabled = true
logs = { invocation_logs = true }
